Finishing mobile version of my portfolio
rivasbolinga/My-first-Portfolio pull request #2
Opened 2022-10-28 22:06 UTC by rivasbolinga

Finishing the mobile version of my portfolio, adding section of projects and about me section

2022-10-28 23:14 UTC, Felix45 requested changes
Hi @rivasbolinga , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] All linter checks are passing :white_check_mark: 
- [ ] Descriptive pull request title and summary :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 

 ![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 23:14 UTC, Felix45 commented on portfolio.html
> +    <section class="works-container">
[ Required ] Please consider fixing the whitespace that appears on your design for screen sizes greater than `320px`, for example at a width of `375px` your implementation of the design introduces a white space on the right margin. Please see the screenshot below and rectify this issue.

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/198748520-e77a910e-0249-4a48-a0a7-d30c60613f32.png" width="300px" />

## Current Implementation
<img src="https://user-images.githubusercontent.com/16392046/198748379-b43cd904-5b77-4dc6-be39-c66e21b76a6b.png" width="300px" />

2022-10-28 23:14 UTC, Felix45 commented on portfolio.html
> +      <div class="about-me-info">
[ Required ] Please consider fixing the whitespace that appears on your design for screen sizes greater than `320px`, for example at a width of `375px` your implementation of the design introduces a white space on the right margin. Please see the screenshot below and rectify this issue.

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/198748751-4ebe6b79-2bcf-40de-a77e-7ecb446c5757.png" width="300px" />

## Current implementation
<img src="https://user-images.githubusercontent.com/16392046/198748147-769febae-ab85-4b2e-910c-2e17e29f2cf2.png" width="300px"/>

2022-10-29 08:40 UTC, fobadara approved these changes
Hi @rivasbolinga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 14:13 UTC, merged