Form section
rivasbolinga/My-first-Portfolio pull request #3
Opened 2022-11-01 22:32 UTC by rivasbolinga

Adding last part of mobile version of my portfolio: Contact-form section and footer  with social media logos,

2022-11-01 23:50 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @rivasbolinga , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 23:50 UTC, ridwanediallo commented on portfolio.html
> +        <form action="https://formspree.io/html/" method="POST" class="form">
- [ ] Hello @rivasbolinga , good job so far 👏. But the form submission is still not working.
 
![Screenshot from 2022-11-01 23-09-05](https://user-images.githubusercontent.com/89228743/199359252-cd54cdf1-cfa5-428e-905f-dcffe9a2ea9d.png)

- [x] What you need first is to create your account at [formspree](https://formspree.io/html/) and then generate the `form_id` by following the steps. 
when you got the `id`, your `action` should be similar to something like this `action="https://formspree.io/f/hgkd1254us"`
- [x] Lastly, please make that a user can successfully submit a `form`. After that is done you can proudly submit it for review. 🤗

2022-11-01 23:50 UTC, ridwanediallo commented on portfolio.html
> +        <form action="https://formspree.io/html/" method="POST" class="form">
## How to get the `action` value ?
[Demo video](https://user-images.githubusercontent.com/89228743/199359877-b51846d3-16b3-488d-92c2-a992ecee2b21.webm)

2022-11-02 15:27 UTC, GiuseppeTG approved these changes
Hi @rivasbolinga  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 : 
Congratulations! 🎉 

![Alt Text](https://media3.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

## Highlights
✅  Good documentation
✅  Changes implemented correctly

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 15:27 UTC, GiuseppeTG commented on portfolio.html
> +          <input name="name" type="text" placeholder="Your name" maxlength="30" required value="Andrea">
- [OPTIONAL] I highly suggest that you remove de value from the inputs, it doesn't let the placeholder do its job 🤓. Also, the user has to erase that value before typing his credentials 👍

2022-11-02 15:29 UTC, merged